list = [ 'Bitwarden',
'TSB (bank)',
'RBS (bank)',
'Lloyds (bank)',
'Monzo (bank)',
'Marcus (bank)',
'Vanguard (Investment)',
'Royal London (Private Pension)',
'Government Gateway (UK NI Pension Tax)',
'Desktop Computer NZXT',
'MacBook Pro 13 inch',
'iPad Air',
'Samsung A50 (phone)',
'ocnarf Gmail',
'kffc Gmail',
'kffc Yahoo email',
'Nation Insurance Number (NI)',
'Passport (Me)',
'Passport UK (Me)',
'Passport (Julie)',
'Student Finance England (Me)',
'Student Finance England (Mum)',
'Student Finance England (Dad)',
'Edocs Official Academic Transcript',
'Exam UCI Number',
'UCAS',
'UoM Login',
'UoM Alumni',
'CareersLink',
'LinkedIn',
'myepaywindow.com',
'Moneybox',
'GP online service (patient-access)',
'ebay',
'Apple',
'Circle Pay',
'PayPal',
'Amazon (Me)',
'Dyson',
'Authy (Authenticator)',
'Virgin Media Broadband Login (Bills)',
'E-on (Bills)',
'One Manchester (Bills)',
'Intel NUC computer (Dad)',
'Council Login (Dad)',
'Amazon (Dad)',
'Netflix (Julie)',
'Intel NUC computer (family)',
'Youtube TV (family)',
'My O2 (Dad)',
'Macau Education Fund',
'Aquatic Centre',
'Sony Experia J (old phone)',
'Luggage Password',
'Hong Kong ID',
'HTC Desire 626 (old phone)',
'House Number',
'Currys PC World',
'Boots',
'PwC',
'Provisional License',
'Stagecoach',
'i2i pipeline outlook 365',
'Manchester Libraries',
'driving theory test pro',
'IKEA',
'My O2 (Me)',
'Tesco',
'Prolific.ac',
'Oculus',
'Samsung Account'
];