list = [ 'Student Finance England (SFE) - Me',
'Student Finance England (SFE) - Mum',
'Student Finance England (SFE) - Dad',
'UCAS',
'University of Manchester (UoM)',
'HSBC (banking)',
'Passport - Portugal (Me)',
'Passport - Portugal (Julie)',
'Passport - UK (Me)',
'NI number (National Insurance)',
'HK ID',
'Luggage password',
'Sony Xperia J (phone) IMEI',
'Apple ID',
'Aquatic Centre',
'kffc Yahoo email',
'oc Gmail',
'kffc Gmail',
'Netflix (Julie)',
'Macau Student Fund',
'GP online service (patient-access)',
'RBS (banking)',
'TSB (banking)',
'Lloyds (banking)',
'Nationwide (banking)',
'Dyson',
'MyO2 (Dad)',
'E-on electric company',
'HTC Desire 626 (phone) IMEI',
'Exam UCI number',
'Amazon',
'MacBook Pro 13 inch',
'iPad Air',
'6 Middlewich Walk',
'Currys PC world',
'Boots',
'PwC',
'Provisional license (driving)',
'LinkedIn login',
'University of Manchester (UoM) Alumni',
'University of Manchester (UoM) online transcript (edocs)',
'CareersLink University of Manchester (UoM)',
'Stagecoach',
'i2i pipelines outlook',
'myepaywindow.com pay slip (payslip)',
'Manchester Libraries (central library)',
'manchester.theorytestpro.co.uk Driving Theory Practice',
'IKEA (Me)',
'MyO2 (Me)',
'Tesco Login and Clubcard',
'PayPal',
'Prolific.ac',
'Circle Pay',
'Royal London',
'Government Gateway',
'Monzo Bank',
'Marcus Bank',
];